version: "3.1"

services:
  mysql_db:
    image: mysql:8.0.12
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: aslkjf2313slkfj
      MYSQL_DATABASE: movie_db
      MYSQL_USER: dockeruser
      MYSQL_PASSWORD: d0cK3r_Us3r
    ports:
      - "3306:3306"
  backend:
    container_name: backend
    image: webdevops/php-apache-dev:7.2
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./backend:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - TMDB_API_KEY=fcf049aaeafe3ad83ee5ff9e33bb786b
  frontend:
    image: node:10.9.0-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start