version: "3.1"

services:
  mysql_db:
    image: mysql:8.0.12
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: aslkjf2313slkfj
      MYSQL_DATABASE: movie_db
      MYSQL_USER: dockeruser
      MYSQL_PASSWORD: d0cK3r_Us3r
    ports:
    - "3306:3306"
  backend:
    image: nginx:1.15.2-alpine
    ports:
    - "8080:8080"
    volumes:
    - ./backend:/code
    - ./backend/site.conf:/etc/nginx/conf.d/site.conf
  php:
    image: chialab/php:7.2
    volumes:
    - ./backend:/code
    links:
      - mysql_db
  frontend:
    image: node:10.9.0-alpine
    ports:
    - "3000:3000"
    volumes:
    - ./frontend:/app
    working_dir: /app