version: "3.1"

services:
  mysql_db:
    image: mysql:8.0.12
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: aslkjf2313slkfj
      MYSQL_DATABASE: movie_db
      MYSQL_USER: dockeruser
      MYSQL_PASSWORD: d0cK3r_Us3r
    ports:
      - "3306:3306"
  detectify:
    container_name: detectify
    image: webdevops/php-apache-dev:7.2
    ports:
      - "3000:80"
      - "443:443"
    volumes:
      - ./backend:/app/backend
      - ./frontend/dist:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app
      - TMDB_API_KEY=fcf049aaeafe3ad83ee5ff9e33bb786b
    working_dir: /app/backend
    depends_on:
      -  mysql_db